# Generated by Django 4.1.7 on 2023-03-10 16:14

from django.db import migrations, models
import django.db.models.deletion
import information.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('url', models.URLField(blank=True, null=True)),
                ('front_page', models.ImageField(default='information/media/default.png', upload_to='information/media', validators=[information.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia', models.ImageField(blank=True, null=True, upload_to='information/media')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='information.advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='information.section'),
        ),
    ]
