runtime: python310
instance_class: F2
service: backend
entrypoint: bash -c 'gunicorn -b :$PORT aiding.wsgi:application --pythonpath "./aiding" && python3 manage.py makemigrations && python3 manage.py migrate'
handlers:
- url: /.*
  script: auto
