# Generated by Django 4.1.7 on 2023-03-05 18:04

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comunication_type', models.CharField(choices=[(partners.models.ComunicationType['TELEFONICA'], 'TELEFÓNICA'), (partners.models.ComunicationType['TELEMATICA'], 'TELEMÁTICA'), (partners.models.ComunicationType['PERSONAL'], 'PERSONAL'), (partners.models.ComunicationType['EMAIL'], 'EMAIL')], max_length=20)),
            ],
        ),
    ]
