# Generated by Django 4.1.7 on 2023-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('state', models.CharField(choices=[('ALTA', 'alta'), ('BAJA', 'baja')], default='alta', max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
