# Generated by Django 4.1.7 on 2023-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='total_donation',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
