# Generated by Django 4.1.7 on 2023-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partners_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='active', max_length=8),
        ),
    ]
