# Generated by Django 4.1.7 on 2023-03-05 12:45

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comunication_type', models.CharField(choices=[(base.models.ComunicationType['TELEFONICA'], 'TELEFÓNICA'), (base.models.ComunicationType['TELEMATICA'], 'TELEMÁTICA'), (base.models.ComunicationType['PERSONAL'], 'PERSONAL'), (base.models.ComunicationType['EMAIL'], 'EMAIL')], max_length=20)),
            ],
        ),
    ]
