name: Deploy gcloud

on: push

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Local config
      uses: actions/checkout@v2

    - name: Install settings
      run: |
        cp aiding/deploy_settings.py aiding/local_settings.py
        echo "${{ secrets.ROOT_PASSWORD }}" >> .env
        echo "${{ secrets.DATABASE_URL }}" >> .env

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCLOUD_CREDENTIALS}} '
    
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        deliverables: app.yaml
        version: v1
      
    - name: Test deploy works
      run: curl "${{ steps.deploy.outputs.url }}"
